---
# reference from https://knowledge.udacity.com/questions/907729
- name: create directory
  become: true
  file:
    path: /home/ubuntu/web
    state: directory
    mode: 0755
- name: copy backend files
  become: true
  copy:
    src:  ~/project/artifact.tar.gz
    dest: /home/ubuntu/web/artifact.tar.gz
- name: extract backend files
  become: true
  shell: |
    cd /home/ubuntu/web
    tar -vxf artifact.tar.gz
    rm artifact.tar.gz
- name: start node
  become: true
  shell: |
    cd /home/ubuntu/web
    npm install
    pm2 stop default
    pm2 start npm -- start
    cd dist
    pm2 start main.js --update-env