---
#   Refer from https://knowledge.udacity.com/questions/907729
- name: create directory
  become: true
  file:
    path: /home/ubuntu/backend
    state: directory
    # mode: 0755
- name: copy backend files
  become: true
  copy:
    src:  /home/circleci/project/artifact.tar.gz
    dest: /home/ubuntu/backend/artifact.tar.gz
- name: extract backend files
  become: true
  shell: |
    cd /home/ubuntu/backend
    tar -vxf artifact.tar.gz
    ls -la
    rm artifact.tar.gz
- name: "npm install and build"
  become: true
  shell: |
    npm install
    npm run build
    pm2 stop default
    pm2 start npm --name backend -- start
  args:  
    chdir: /home/ubuntu/backend
- name: start node
  become: true
  shell: |
    # cd /home/ubuntu/backend
    # npm install
    # npm run build
    # pm2 stop default
    # pm2 start npm --name backend -- start
    # cd dist
    # pm2 start main.js --update-env
    pm2 start -f ./main.js
  args:  
    chdir: /home/ubuntu/backend/dist